-- FarmaGest production schema for Supabase/Postgres.
-- Apply in a Supabase project after reviewing roles and backup policy.

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;
create extension if not exists unaccent;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to authenticated;

create or replace function public.farmagest_unaccent(value text)
returns text
language sql
immutable
parallel safe
strict
set search_path = ''
as $$
  select public.unaccent('public.unaccent', value);
$$;

create type public.user_role as enum ('ADMIN', 'CAJERO');
create type public.unidad_medida as enum ('UNIDAD', 'ENVASE');
create type public.forma_pago as enum ('EFECTIVO', 'QR', 'TARJETA', 'CREDITO');
create type public.estado_venta as enum ('CERRADA', 'ANULADA');
create type public.estado_arqueo as enum ('ABIERTO', 'CERRADO', 'AUDITADO');

create table public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre_completo text not null,
  rol public.user_role not null default 'CAJERO',
  activo boolean not null default true,
  fecha_creacion timestamptz not null default now()
);

create table public.laboratorios (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  direccion text,
  telefono text,
  contacto text,
  activo boolean not null default true
);

create table public.productos (
  id uuid primary key default gen_random_uuid(),
  codigo_interno text unique not null,
  nombre_comercial text not null,
  principio_activo text,
  laboratorio_id uuid references public.laboratorios(id),
  presentacion text,
  unidad_medida public.unidad_medida not null,
  cantidad_por_envase integer not null default 1 check (cantidad_por_envase > 0),
  costo_unitario numeric(10,2) not null check (costo_unitario >= 0),
  precio_venta numeric(10,2) not null check (precio_venta >= 0),
  stock_minimo integer not null default 5 check (stock_minimo >= 0),
  iva boolean not null default false,
  activo boolean not null default true,
  fecha_creacion timestamptz not null default now()
);

create table public.lotes (
  id uuid primary key default gen_random_uuid(),
  producto_id uuid not null references public.productos(id) on delete cascade,
  numero_lote text not null,
  fecha_vencimiento date not null,
  cantidad_disponible integer not null check (cantidad_disponible >= 0),
  costo_compra numeric(10,2) not null check (costo_compra >= 0),
  fecha_ingreso date not null default current_date,
  proveedor text,
  factura_compra text,
  unique (producto_id, numero_lote)
);

create table public.ventas (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references public.perfiles(id),
  fecha timestamptz not null default now(),
  subtotal numeric(10,2) not null check (subtotal >= 0),
  descuento numeric(10,2) not null default 0 check (descuento >= 0),
  iva numeric(10,2) not null default 0 check (iva >= 0),
  total numeric(10,2) not null check (total >= 0),
  forma_pago public.forma_pago not null,
  cliente_nombre text,
  cliente_telefono text,
  estado public.estado_venta not null default 'CERRADA',
  fecha_anulacion timestamptz,
  motivo_anulacion text,
  numero_ticket bigint generated by default as identity unique
);

create table public.detalle_ventas (
  id uuid primary key default gen_random_uuid(),
  venta_id uuid not null references public.ventas(id) on delete cascade,
  lote_id uuid not null references public.lotes(id),
  producto_id uuid not null references public.productos(id),
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(10,2) not null check (precio_unitario >= 0),
  costo_unitario numeric(10,2) not null check (costo_unitario >= 0),
  subtotal numeric(10,2) not null check (subtotal >= 0)
);

create table public.compras (
  id uuid primary key default gen_random_uuid(),
  proveedor text not null,
  fecha date not null default current_date,
  factura_numero text,
  total numeric(10,2) not null check (total >= 0),
  usuario_id uuid not null references public.perfiles(id),
  observaciones text,
  fecha_creacion timestamptz not null default now()
);

create table public.detalle_compras (
  id uuid primary key default gen_random_uuid(),
  compra_id uuid not null references public.compras(id) on delete cascade,
  producto_id uuid not null references public.productos(id),
  lote_id uuid not null references public.lotes(id),
  cantidad integer not null check (cantidad > 0),
  costo_unitario numeric(10,2) not null check (costo_unitario >= 0),
  subtotal numeric(10,2) not null check (subtotal >= 0)
);

create table public.configuracion (
  id uuid primary key default gen_random_uuid(),
  clave text unique not null,
  valor text not null,
  descripcion text,
  fecha_actualizacion timestamptz not null default now()
);

create table public.arqueos_caja (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references public.perfiles(id),
  fecha date not null default current_date,
  hora_apertura timestamptz not null default now(),
  hora_cierre timestamptz,
  fondo_inicial numeric(10,2) not null check (fondo_inicial >= 0),
  ventas_efectivo numeric(10,2) not null default 0 check (ventas_efectivo >= 0),
  ventas_tarjeta numeric(10,2) not null default 0 check (ventas_tarjeta >= 0),
  ventas_credito numeric(10,2) not null default 0 check (ventas_credito >= 0),
  gastos_dia numeric(10,2) not null default 0 check (gastos_dia >= 0),
  retiros_caja numeric(10,2) not null default 0 check (retiros_caja >= 0),
  efectivo_esperado numeric(10,2) generated always as
    (fondo_inicial + ventas_efectivo - gastos_dia - retiros_caja) stored,
  efectivo_contado numeric(10,2),
  diferencia numeric(10,2) generated always as
    (coalesce(efectivo_contado, 0) - (fondo_inicial + ventas_efectivo - gastos_dia - retiros_caja)) stored,
  justificacion text,
  autorizado_por uuid references public.perfiles(id),
  estado public.estado_arqueo not null default 'ABIERTO',
  unique (usuario_id, fecha),
  constraint arqueo_cierre_consistente check (
    (estado = 'ABIERTO' and hora_cierre is null and efectivo_contado is null)
    or (estado in ('CERRADO', 'AUDITADO') and hora_cierre is not null and efectivo_contado is not null)
  )
);

create index perfiles_rol_idx on public.perfiles (rol);
create index productos_laboratorio_id_idx on public.productos (laboratorio_id);
create index productos_activos_idx on public.productos (codigo_interno) where activo = true;
create index productos_nombre_trgm_idx on public.productos using gin (public.farmagest_unaccent(lower(nombre_comercial)) gin_trgm_ops) where activo = true;
create index productos_principio_trgm_idx on public.productos using gin (public.farmagest_unaccent(lower(coalesce(principio_activo, ''))) gin_trgm_ops) where activo = true;
create index lotes_producto_id_idx on public.lotes (producto_id);
create index lotes_vencimiento_disponible_idx on public.lotes (fecha_vencimiento, producto_id) where cantidad_disponible > 0;
create index ventas_usuario_fecha_idx on public.ventas (usuario_id, fecha desc);
create index ventas_fecha_estado_idx on public.ventas (fecha desc, estado);
create index detalle_ventas_venta_id_idx on public.detalle_ventas (venta_id);
create index detalle_ventas_producto_id_idx on public.detalle_ventas (producto_id);
create index compras_usuario_fecha_idx on public.compras (usuario_id, fecha desc);
create index detalle_compras_compra_id_idx on public.detalle_compras (compra_id);
create index detalle_compras_producto_id_idx on public.detalle_compras (producto_id);
create index detalle_compras_lote_id_idx on public.detalle_compras (lote_id);
create index arqueos_usuario_fecha_idx on public.arqueos_caja (usuario_id, fecha desc);

alter table public.perfiles enable row level security;
alter table public.laboratorios enable row level security;
alter table public.productos enable row level security;
alter table public.lotes enable row level security;
alter table public.ventas enable row level security;
alter table public.detalle_ventas enable row level security;
alter table public.compras enable row level security;
alter table public.detalle_compras enable row level security;
alter table public.configuracion enable row level security;
alter table public.arqueos_caja enable row level security;

revoke all on public.perfiles, public.laboratorios, public.productos, public.lotes, public.ventas, public.detalle_ventas, public.compras, public.detalle_compras, public.configuracion, public.arqueos_caja from anon, authenticated;
grant select on public.laboratorios, public.productos, public.lotes to authenticated;
grant select on public.perfiles, public.ventas, public.detalle_ventas, public.compras, public.detalle_compras, public.configuracion, public.arqueos_caja to authenticated;
grant insert on public.productos, public.lotes, public.laboratorios to authenticated;
grant update on public.productos, public.lotes, public.laboratorios to authenticated;
grant insert, update on public.compras, public.detalle_compras to authenticated;
grant update on public.configuracion to authenticated;
grant insert, update on public.arqueos_caja to authenticated;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.perfiles p
    where p.id = (select auth.uid())
      and p.activo = true
      and p.rol = 'ADMIN'
  );
$$;

revoke all on function private.is_admin() from public, anon;
grant execute on function private.is_admin() to authenticated;

create policy perfiles_select_self_or_admin on public.perfiles
for select to authenticated
using ((select auth.uid()) = id or private.is_admin());

create policy catalogos_select_auth on public.laboratorios
for select to authenticated
using (true);

create policy productos_select_auth on public.productos
for select to authenticated
using (activo = true or private.is_admin());

create policy lotes_select_auth on public.lotes
for select to authenticated
using (exists (
  select 1 from public.productos p
  where p.id = lotes.producto_id and (p.activo = true or private.is_admin())
));

create policy admin_insert_laboratorios on public.laboratorios
for insert to authenticated
with check (private.is_admin());

create policy admin_update_laboratorios on public.laboratorios
for update to authenticated
using (private.is_admin())
with check (private.is_admin());

create policy admin_write_productos on public.productos
for all to authenticated
using (private.is_admin())
with check (private.is_admin());

create policy admin_write_lotes on public.lotes
for all to authenticated
using (private.is_admin())
with check (private.is_admin());

create policy ventas_select_own_or_admin on public.ventas
for select to authenticated
using (usuario_id = (select auth.uid()) or private.is_admin());

create policy detalle_select_own_or_admin on public.detalle_ventas
for select to authenticated
using (exists (
  select 1 from public.ventas v
  where v.id = detalle_ventas.venta_id
    and (v.usuario_id = (select auth.uid()) or private.is_admin())
));

create policy compras_select_own_or_admin on public.compras
for select to authenticated
using (usuario_id = (select auth.uid()) or private.is_admin());

create policy compras_insert_own on public.compras
for insert to authenticated
with check (usuario_id = (select auth.uid()));

create policy compras_update_admin on public.compras
for update to authenticated
using (private.is_admin())
with check (private.is_admin());

create policy detalle_compras_select_own_or_admin on public.detalle_compras
for select to authenticated
using (exists (
  select 1 from public.compras c
  where c.id = detalle_compras.compra_id
    and (c.usuario_id = (select auth.uid()) or private.is_admin())
));

create policy detalle_compras_write_admin on public.detalle_compras
for all to authenticated
using (private.is_admin())
with check (private.is_admin());

create policy configuracion_select_auth on public.configuracion
for select to authenticated
using (true);

create policy configuracion_update_admin on public.configuracion
for update to authenticated
using (private.is_admin())
with check (private.is_admin());

create policy arqueos_select_own_or_admin on public.arqueos_caja
for select to authenticated
using (usuario_id = (select auth.uid()) or private.is_admin());

create policy arqueos_insert_own on public.arqueos_caja
for insert to authenticated
with check (usuario_id = (select auth.uid()));

create policy arqueos_update_own_open_or_admin on public.arqueos_caja
for update to authenticated
using (usuario_id = (select auth.uid()) or private.is_admin())
with check (usuario_id = (select auth.uid()) or private.is_admin());

create or replace function public.buscar_productos_venta(search_term text)
returns table (
  id uuid,
  codigo_interno text,
  nombre_comercial text,
  principio_activo text,
  presentacion text,
  cantidad_por_envase integer,
  costo_unitario numeric,
  precio_venta numeric,
  margen_unitario numeric,
  margen_porcentaje numeric,
  stock_total bigint,
  lotes jsonb
)
language sql
stable
security invoker
as $$
  select
    p.id,
    p.codigo_interno,
    p.nombre_comercial,
    p.principio_activo,
    p.presentacion,
    p.cantidad_por_envase,
    p.costo_unitario,
    p.precio_venta,
    (p.precio_venta - p.costo_unitario) as margen_unitario,
    case
      when p.precio_venta > 0 then round(((p.precio_venta - p.costo_unitario) / p.precio_venta) * 100, 2)
      else 0
    end as margen_porcentaje,
    coalesce(sum(l.cantidad_disponible), 0)::bigint as stock_total,
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'id', l.id,
          'numeroLote', l.numero_lote,
          'fechaVencimiento', l.fecha_vencimiento,
          'cantidadDisponible', l.cantidad_disponible
        )
        order by l.fecha_vencimiento asc
      ) filter (where l.id is not null),
      '[]'::jsonb
    ) as lotes
  from public.productos p
  join public.lotes l on l.producto_id = p.id
  where p.activo = true
    and l.cantidad_disponible > 0
    and l.fecha_vencimiento > current_date
    and (
      public.farmagest_unaccent(lower(p.nombre_comercial)) like '%' || public.farmagest_unaccent(lower(search_term)) || '%'
      or public.farmagest_unaccent(lower(coalesce(p.principio_activo, ''))) like '%' || public.farmagest_unaccent(lower(search_term)) || '%'
      or lower(p.codigo_interno) like '%' || lower(search_term) || '%'
    )
  group by p.id, p.codigo_interno, p.nombre_comercial, p.principio_activo, p.presentacion, p.cantidad_por_envase, p.costo_unitario, p.precio_venta
  order by p.nombre_comercial
  limit 25;
$$;

revoke all on function public.buscar_productos_venta(text) from public, anon;
grant execute on function public.buscar_productos_venta(text) to authenticated;

create or replace function public.crear_venta(
  p_items jsonb,
  p_forma_pago public.forma_pago,
  p_cliente_nombre text default null,
  p_cliente_telefono text default null,
  p_descuento numeric default 0
)
returns table (venta_id uuid, numero_ticket bigint, total numeric)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_venta_id uuid;
  v_subtotal numeric(10,2) := 0;
  v_total numeric(10,2);
  v_ticket bigint;
  v_item record;
  v_lote record;
  v_factor integer;
  v_cantidad_unidades integer;
  v_precio_cobro numeric(10,2);
  v_costo_cobro numeric(10,2);
begin
  if v_user_id is null then
    raise exception 'No autenticado' using errcode = '28000';
  end if;

  if not exists (select 1 from public.perfiles where id = v_user_id and activo = true) then
    raise exception 'Usuario inactivo o no registrado' using errcode = '28000';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'La venta no tiene items';
  end if;

  if p_descuento < 0 then
    raise exception 'Descuento invalido';
  end if;

  for v_item in
    select lote_id, modo_venta, sum(cantidad)::integer as cantidad
    from (
      select
        nullif(value->>'lote_id', '')::uuid as lote_id,
        coalesce(nullif(value->>'modo_venta', ''), 'UNIDAD') as modo_venta,
        nullif(value->>'cantidad', '')::integer as cantidad
      from jsonb_array_elements(p_items)
    ) parsed_items
    group by lote_id, modo_venta
  loop
    if v_item.lote_id is null or v_item.cantidad is null or v_item.cantidad <= 0 then
      raise exception 'Cantidad invalida';
    end if;

    if v_item.modo_venta not in ('UNIDAD', 'CAJA') then
      raise exception 'Forma de venta invalida';
    end if;

    select
      l.id as lote_id,
      l.cantidad_disponible,
      l.fecha_vencimiento,
      l.costo_compra,
      p.id as producto_id,
      p.precio_venta,
      p.cantidad_por_envase,
      p.activo
    into v_lote
    from public.lotes l
    join public.productos p on p.id = l.producto_id
    where l.id = v_item.lote_id
    for update of l;

    if not found then
      raise exception 'Lote no encontrado';
    end if;

    if v_lote.activo is false then
      raise exception 'Producto inactivo';
    end if;

    if v_lote.fecha_vencimiento <= current_date then
      raise exception 'No se puede vender un lote vencido';
    end if;

    v_factor := greatest(coalesce(v_lote.cantidad_por_envase, 1), 1);

    if v_item.modo_venta = 'CAJA' then
      v_cantidad_unidades := v_item.cantidad * v_factor;
      v_precio_cobro := v_lote.precio_venta;
      v_costo_cobro := v_lote.costo_compra;
    else
      v_cantidad_unidades := v_item.cantidad;
      v_precio_cobro := round(v_lote.precio_venta / v_factor, 2);
      v_costo_cobro := round(v_lote.costo_compra / v_factor, 2);
    end if;

    if v_lote.cantidad_disponible < v_cantidad_unidades then
      raise exception 'Stock insuficiente';
    end if;

    v_subtotal := v_subtotal + (v_precio_cobro * v_item.cantidad);
  end loop;

  if p_descuento > v_subtotal then
    raise exception 'El descuento supera el subtotal';
  end if;

  v_total := v_subtotal - p_descuento;

  insert into public.ventas (
    usuario_id, subtotal, descuento, iva, total, forma_pago, cliente_nombre, cliente_telefono
  )
  values (
    v_user_id, v_subtotal, p_descuento, 0, v_total, p_forma_pago, p_cliente_nombre, p_cliente_telefono
  )
  returning id, numero_ticket into v_venta_id, v_ticket;

  for v_item in
    select lote_id, modo_venta, sum(cantidad)::integer as cantidad
    from (
      select
        nullif(value->>'lote_id', '')::uuid as lote_id,
        coalesce(nullif(value->>'modo_venta', ''), 'UNIDAD') as modo_venta,
        nullif(value->>'cantidad', '')::integer as cantidad
      from jsonb_array_elements(p_items)
    ) parsed_items
    group by lote_id, modo_venta
  loop
    select
      l.id as lote_id,
      l.cantidad_disponible,
      l.fecha_vencimiento,
      l.costo_compra,
      p.id as producto_id,
      p.precio_venta,
      p.cantidad_por_envase
    into v_lote
    from public.lotes l
    join public.productos p on p.id = l.producto_id
    where l.id = v_item.lote_id
    for update of l;

    if not found then
      raise exception 'Lote no encontrado';
    end if;

    v_factor := greatest(coalesce(v_lote.cantidad_por_envase, 1), 1);

    if v_item.modo_venta = 'CAJA' then
      v_cantidad_unidades := v_item.cantidad * v_factor;
      v_precio_cobro := v_lote.precio_venta;
      v_costo_cobro := v_lote.costo_compra;
    else
      v_cantidad_unidades := v_item.cantidad;
      v_precio_cobro := round(v_lote.precio_venta / v_factor, 2);
      v_costo_cobro := round(v_lote.costo_compra / v_factor, 2);
    end if;

    insert into public.detalle_ventas (
      venta_id, lote_id, producto_id, cantidad, precio_unitario, costo_unitario, subtotal
    )
    values (
      v_venta_id,
      v_lote.lote_id,
      v_lote.producto_id,
      v_item.cantidad,
      v_precio_cobro,
      v_costo_cobro,
      v_precio_cobro * v_item.cantidad
    );

    update public.lotes
    set cantidad_disponible = cantidad_disponible - v_cantidad_unidades
    where id = v_lote.lote_id;
  end loop;

  return query select v_venta_id, v_ticket, v_total;
end;
$$;

revoke all on function public.crear_venta(jsonb, public.forma_pago, text, text, numeric) from public, anon;
grant execute on function public.crear_venta(jsonb, public.forma_pago, text, text, numeric) to authenticated;

create or replace function public.anular_venta(
  p_venta_id uuid,
  p_motivo text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_venta record;
  v_detalle record;
begin
  if v_user_id is null then
    raise exception 'No autenticado' using errcode = '28000';
  end if;

  select *
  into v_venta
  from public.ventas
  where id = p_venta_id
  for update;

  if not found then
    raise exception 'Venta no encontrada';
  end if;

  if v_venta.usuario_id <> v_user_id and not private.is_admin() then
    raise exception 'No autorizado' using errcode = '42501';
  end if;

  if v_venta.estado = 'ANULADA' then
    raise exception 'La venta ya fue anulada';
  end if;

  for v_detalle in
    select lote_id, cantidad
    from public.detalle_ventas
    where venta_id = p_venta_id
    for update
  loop
    update public.lotes
    set cantidad_disponible = cantidad_disponible + v_detalle.cantidad
    where id = v_detalle.lote_id;
  end loop;

  update public.ventas
  set estado = 'ANULADA',
      fecha_anulacion = now(),
      motivo_anulacion = nullif(trim(p_motivo), '')
  where id = p_venta_id;

  return true;
end;
$$;

revoke all on function public.anular_venta(uuid, text) from public, anon;
grant execute on function public.anular_venta(uuid, text) to authenticated;

create or replace function public.obtener_ticket(p_venta_id uuid)
returns jsonb
language sql
stable
security invoker
as $$
  select jsonb_build_object(
    'ventaId', v.id,
    'numeroTicket', v.numero_ticket,
    'fecha', v.fecha,
    'formaPago', v.forma_pago,
    'estado', v.estado,
    'subtotal', v.subtotal,
    'descuento', v.descuento,
    'iva', v.iva,
    'total', v.total,
    'items', coalesce(
      jsonb_agg(
        jsonb_build_object(
          'producto', p.nombre_comercial,
          'presentacion', p.presentacion,
          'lote', l.numero_lote,
          'cantidad', d.cantidad,
          'precioUnitario', d.precio_unitario,
          'subtotal', d.subtotal
        )
        order by p.nombre_comercial
      ) filter (where d.id is not null),
      '[]'::jsonb
    )
  )
  from public.ventas v
  left join public.detalle_ventas d on d.venta_id = v.id
  left join public.productos p on p.id = d.producto_id
  left join public.lotes l on l.id = d.lote_id
  where v.id = p_venta_id
  group by v.id;
$$;

revoke all on function public.obtener_ticket(uuid) from public, anon;
grant execute on function public.obtener_ticket(uuid) to authenticated;

create or replace function public.abrir_arqueo(p_fondo_inicial numeric)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_arqueo_id uuid;
begin
  if v_user_id is null then
    raise exception 'No autenticado' using errcode = '28000';
  end if;

  if p_fondo_inicial < 0 then
    raise exception 'Fondo inicial invalido';
  end if;

  insert into public.arqueos_caja (usuario_id, fecha, fondo_inicial)
  values (v_user_id, current_date, p_fondo_inicial)
  returning id into v_arqueo_id;

  return v_arqueo_id;
end;
$$;

revoke all on function public.abrir_arqueo(numeric) from public, anon;
grant execute on function public.abrir_arqueo(numeric) to authenticated;

create or replace function public.cerrar_arqueo(
  p_efectivo_contado numeric,
  p_gastos_dia numeric default 0,
  p_retiros_caja numeric default 0,
  p_justificacion text default null,
  p_autorizado_por uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_arqueo record;
  v_efectivo numeric(10,2);
  v_tarjeta numeric(10,2);
  v_credito numeric(10,2);
  v_diferencia numeric(10,2);
begin
  if v_user_id is null then
    raise exception 'No autenticado' using errcode = '28000';
  end if;

  if p_efectivo_contado < 0 or p_gastos_dia < 0 or p_retiros_caja < 0 then
    raise exception 'Montos invalidos';
  end if;

  select *
  into v_arqueo
  from public.arqueos_caja
  where usuario_id = v_user_id
    and fecha = current_date
    and estado = 'ABIERTO'
  for update;

  if not found then
    raise exception 'No hay caja abierta para cerrar';
  end if;

  select
    coalesce(sum(total) filter (where forma_pago = 'EFECTIVO' and estado = 'CERRADA'), 0),
    coalesce(sum(total) filter (where forma_pago in ('QR', 'TARJETA') and estado = 'CERRADA'), 0),
    coalesce(sum(total) filter (where forma_pago = 'CREDITO' and estado = 'CERRADA'), 0)
  into v_efectivo, v_tarjeta, v_credito
  from public.ventas
  where usuario_id = v_user_id
    and fecha >= v_arqueo.hora_apertura
    and fecha <= now();

  v_diferencia := p_efectivo_contado - (v_arqueo.fondo_inicial + v_efectivo - p_gastos_dia - p_retiros_caja);

  if abs(v_diferencia) > 10 then
    if p_autorizado_por is null or not exists (
      select 1
      from public.perfiles
      where id = p_autorizado_por
        and rol = 'ADMIN'
        and activo = true
    ) then
      raise exception 'Diferencia requiere autorizacion de administrador';
    end if;

    if nullif(trim(coalesce(p_justificacion, '')), '') is null then
      raise exception 'Diferencia requiere justificacion';
    end if;
  end if;

  update public.arqueos_caja
  set hora_cierre = now(),
      ventas_efectivo = v_efectivo,
      ventas_tarjeta = v_tarjeta,
      ventas_credito = v_credito,
      gastos_dia = p_gastos_dia,
      retiros_caja = p_retiros_caja,
      efectivo_contado = p_efectivo_contado,
      justificacion = nullif(trim(coalesce(p_justificacion, '')), ''),
      autorizado_por = p_autorizado_por,
      estado = 'CERRADO'
  where id = v_arqueo.id;

  return v_arqueo.id;
end;
$$;

revoke all on function public.cerrar_arqueo(numeric, numeric, numeric, text, uuid) from public, anon;
grant execute on function public.cerrar_arqueo(numeric, numeric, numeric, text, uuid) to authenticated;

insert into public.configuracion (clave, valor, descripcion)
values
  ('DIAS_ALERTA_VENCIMIENTO', '30,15,7', 'Dias para alertas de vencimiento'),
  ('MONTO_MAX_DIFERENCIA', '10', 'Monto maximo de diferencia sin autorizacion'),
  ('IVA_POR_DEFECTO', '0', 'Porcentaje de IVA por defecto'),
  ('NOMBRE_FARMACIA', 'Mi Farmacia', 'Nombre que aparece en comprobantes')
on conflict (clave) do update
set valor = excluded.valor,
    descripcion = excluded.descripcion,
    fecha_actualizacion = now();

